services:
  ws-server:
    container_name: ws-server
    image: ghcr.io/shipi1/ws-sensor-server:latest
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - web
      - default

networks:
  web:
    external: true
